---
title: "Dr. Alvaro E. Cordero-Franco"
subtitle: "Researcher"
output: html_document
---

## Educación

El Dr. Álvaro Eduardo Cordero Franco tiene licenciatura en matemáticas por la Facultad de Ciencias Físico - Matemáticas de la Universidad Autónoma de Nuevo León, doctorado en ciencias de la ingeniería con especialidad en ingeniería industrial en el instituto tecnológico de estudios superiores de Monterrey (ITESM) Campus Monterrey. Ph. D, in Systems and Engineering Management, Texas Tech University, Lubbock, TX.

 

Sistema Nacional de Investigadores: Si, SIN I hasta diciembre 2020

Perfil deseable PROMEP: Si, hasta Julio 2021

## Experiencia Docente

## Tesis Dirigidas

Samuel U. Armendariz Hernández. Hypothesis test for changes in variance using a statistic based in P-values in a time series of normal independent observations. Maestría.

Armando Ortega Rosales. Los problemas binivel lineales con coeficientes intervalos en los lados derechos de las restricciones del nivel inferior. Maestría.

Montserrat Delgado Brito. Diseño Económico de la Carta de Control de Tukey Modificada. Mestría.

María Isabel Salazar Alvarez. A Nonparametric capability analysis incorporating quantile sampling in manufacturing processes. Doctorado.

Armando Jesús Guerrero Serrano. Aligned-rank transformation methods in nonparametric tests for homoscedasticity. Maestría.

## Experiencia Profesional

(Noviembre 2019 -presente), Subdirector de Posgrado de la  Facultad de Ciencias Físico Matemáticas, UANL.

(Julio 2016 - Noviembre 2019), Coordinador de la Licenciatura en Matemáticas en la Facultad de Ciencias Físico Matemáticas, UANL

(2013 – presente), Instructor del curso de Estadística Aplicada para la Toma de Decisiones y de Control Estadístico de Procesos que se imparte en el Departamento de Educación Continua de la Facultad de Ciencias Físico Matemáticas, UANL.

(Enero 2010-presente),  Profesor Titular A T. C, Facultad de Ciencias Físico Matemáticas, y del centro de Investigación en Ciencias Físico Matemáticas, UANL

(2007 - 2009), Asistente de Investigación, Cátedra de Investigación en Métodos de Solución de Problemas de Programación Binivel, ITESM, Monterrey, NL

(2007-2009), Asistente de Investigación, Departamento de Ingeniería Industrial, Texas Tech University, Lubbock, TX. USA

(2008-2009), Consultor Asistente, Programa Seis Sigma, ITESM, Monterrey, NL
 

## Proyectos de investigación

Análisis del punto de cambio en series de tiempo con aplicación en control estadístico de procesos, PAICYT 2011 (Terminado).

Análisis del punto de cambio en series de tiempo con aplicación en control estadístico de procesos, PROMEP 2011 (Terminado).

Desarrollo de capacidades tecnológicas para reconstrucción de imágenes 3d para piezas de gran tamaño, que permita su evaluación dimensional mediante el procesamiento, manipulación, inspección y diagnóstico de fallas. Etapa 3. Proyecto CONACYT-PROINNOVA 2012 en colaboración con DEMAQ Technologies y el Tecnológico de Monterrey. (Terminado, Co-responsable técnico).

Desarrollo de capacidades tecnológicas para reconstrucción de imágenes 3d para piezas de gran tamaño, que permita su evaluación dimensional mediante el procesamiento, manipulación, inspección y diagnóstico de fallas. Etapa 3. Proyecto CONACYT-PROINNOVA 2013 en colaboración con DEMAQ Technologies y el Tecnológico de Monterrey. (Terminado, Co-responsable técnico).

Sistema de Predicción de Delitos, SPRED. Proyecto de la FCFM con el Municipio de General Escobedo, N.L. 2018. Terminado

## Publicaciones

Salazar-Alvarez, M; Tercero Gómez, V.; Temblador-Pérez, M; Cordero-Franco, A.; and Conover, W. (2014). Nonparametric analysis of interactions: a review and gap analysis. Proceedings of the 2014 Industrial and Systems Engineering Research Conference Y. Guan and H. Liao, eds.

Javier Morales; Víctor Tercero; José-Fernando Camacho-Vallejo; Alvaro E.Cordero; Luis E. López Nerio; F-Javier Almaguer (2016) Trend and fractality assessment of Mexico's stock exchange, Applied Mathematics and Computation.

María I. Salazar-Alvarez; Carmen Temblador-Pérez; William J. Conover; Víctor G. Tercero-Gómez; Alvaro E. Cordero-Franco; Mario G. Beruvides (2016) Regressing sample quantiles to perform nonparametric capability analysis, International Journal of Advanced Manufacturing Technology.

Barraza-Barraza, D., Tercero-Gómez, V. G., Beruvides, M. G., & Cordero-Franco, A. E. (2017). Remarks on estimating the remaining useful life of an asset in the presence of condition variable changes. In IIE Annual Conference. Proceedings (pp. 1613-1618). Institute of Industrial and Systems Engineers (IISE).

W. J. Conover; Víctor G. Tercero-Gómez; Alvaro E. Cordero-Franco (2017) The sequential normal scores transformation, Sequential Analysis.

Jorge Garza-Venegas; Victor Tercero-Gomez; Alvaro Cordero Franco; María Temblador-Pérez; Mario Beruvides (2017) An evaluation of change-point estimators for a sequence of normal observations with unknown parameters, Communications in Statistics: Simulation and Computation.

Elena Cristina Villanueva-Guerra; Víctor Gustavo Tercero-Gómez; Alvaro Eduardo Cordero-Franco; William Jay Conover (2017) A control chart for variance based on squared ranks, Journal of Statistical Computation and Simulation.

Alcántar-Muñoz, J. E., Barraza-Barraza, D., & Cordero-Franco, A. E. (2018). A STATE-OF-THE-ART REVIEW ON RESEARCH ABOUT THE INCORPORATION OF EQUIPMENT OPERATING CONDITIONS IN CONDITION-BASED MAINTENANCE. In Proceedings of the International Annual Conference of the American Society for Engineering Management. (pp. 1-9). American Society for Engineering Management (ASEM).

Samuel Nucamendi-Guillén; Francisco Angel-Bello; Iris Martínez-Salazar; Alvaro E. Cordero-Franco (2018) The cumulative capacitated vehicle routing problem: New formulations and iterated greedy algorithms, EXPERT SYSTEMS WITH APPLICATIONS.

Víctor Tercero‐Gómez; Victor Aguilar‐Lleyda; Alvaro Cordero‐Franco; William Conover (2020) A distribution free CUSUM chart for joint monitoring of location and scale based on the combination of Wilcoxon and Mood statistics, QUALITY AND RELIABILITY ENGINEERING INTERNATIONAL.

## Cursos

## Conferencias y Congresos

Victor Tercero; William J. Conover (2016). Sequential normal scores in statistical process contrl. XIV Latin American Congress in Probability and Mathematical Statistics CLAPEM.

(2018). 51 Congreso de la Sociedad Matemática Mexicana.

(2019). 52 Congreso Nacional de la Sociedad Matemática Mexicana.

Desarrollo Y Comparación De Un Algoritmo De Construcción Y Un Algoritmo Evolutivo Para La Solución. Seminario.